### ISSUE TITLE
run.sh script not working

### ISSUE THREAD

**Issue by narcis2007** [ava-labs/spacesvm#110]
I am trying to test the VM and the run script does not work in both testing or dev mode, it is stuck at `waiting for all nodes to report healthy...`, other times I get 
```
{"level":"warn","ts":"2022-05-31T09:20:37.850Z","caller":"server/server.go:387","msg":"start custom VMs failed to complete","error":"context deadline exceeded"}
panic: context deadline exceeded

goroutine 49 [running]:
github.com/ava-labs/avalanche-network-runner/server.(*server).Start.func1()
        /home/runner/work/avalanche-network-runner/avalanche-network-runner/server/server.go:388 +0x756
created by github.com/ava-labs/avalanche-network-runner/server.(*server).Start
        /home/runner/work/avalanche-network-runner/avalanche-network-runner/server/server.go:358 +0x19e5
```

can you please fix the script or is it something else that I need to do?

Another Issue I have is that the e2e tests are triggered no matter if I start the script with E2E=true or not and they always fail because of the connection to the nodes is refused

**Comment by narcis2007** [comment]
> @narcis2007 thanks for the report can you confirm what version or branch you are testing against?

I was on master

**Comment by patrick-ogrady** [comment]
Very interesting. I just ran the tip of master on MacOS and it worked without issue (`./scripts/run.sh 1.7.11`):
```
cluster is ready!
endpoint: /ext/bc/7L6nfNiN4VQuDfKmx7Y54hX8iyhWapn8tPLQznthmXR1BLgvX
logsDir: /var/folders/mp/6jm81gc11dv3xtcwxmrd8mcr0000gn/T/network-runner-root-data3589321946
pid: 44896
uris:
- http://127.0.0.1:42144
- http://127.0.0.1:44155
- http://127.0.0.1:46394
- http://127.0.0.1:59969
- http://127.0.0.1:63891
network-runner RPC server is running on PID 44895...

use the following command to terminate:

pkill -P 44895 && kill -2 44895 && pkill -9 -f sqja3uK17MJxfC7AN8nGadBw9JK5BcrsNwNynsqP5Gih8M5Bm
```

Thanks for finding the regression where we always run E2E. We've put up a PR to skip the `ClaimTx/SetTx` tests: #111.
