### ISSUE TITLE
Error When I tried to visit my space

### ISSUE THREAD

**Issue by ArturVargas** [ava-labs/spacesvm#91]
I'm claimed an space but when I tried to visit it the console shows me and error
Steps to replicate the error:
Connect Metamask Account (Avalanche Mainnet-C)
Search an namespace availability
Claim the space
Firm the transaction
Visit my Spaces

https://user-images.githubusercontent.com/21693926/150410390-24240729-41e6-4a8c-a10e-4f5a6f563e3e.mov

**Comment by nahoc10** [comment]
I can't replicate this right now. 

Maybe it was a corrupted deploy that got cached? Have you tried hard refreshing your browser?

**Comment by ArturVargas** [comment]
> I can't replicate this right now.
> 
> Maybe it was a corrupted deploy that got cached? Have you tried hard refreshing your browser?

Yes I deleted my cache and refreshing, now it's working thanks!
